apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-rules
  namespace: monitoring
  labels:
    release: prometheus

spec:
  groups:
  - name: custom.rules
    rules:

    - alert: PodNotRunning
      expr: |
        kube_pod_status_phase{phase!="Running"} == 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is not running"
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is not in the Running state for more than 5 minutes."


    - alert: LackOfDiskSpace
      expr: ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 25 and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Host out of disk space (instance {{ $labels.instance }})
        description: Disk is almost full. The remaining disk capacity is = {{ $value | printf "%.0f" }}%


    - alert: HighMemoryUsage
      expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Host out of memory (instance {{ $labels.instance }})
        description: "Node memory is filling up (< 10% left)\n.  The current memory usage is = {{ $value | printf \"%.0f\" }}%\n"

 
    - alert: HighCPUUsage
      expr: 100 * (1 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m]))) > 90
      for: 5m
      labels:
        severity: critical      
      annotations:
        summary: "High CPU usage"
        description: |
          CPU usage is above 90% for the last 5 minutes. The current CPU usage is = {{ $value | printf "%.0f" }}%     